# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02\x61i\")\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"$\n\x11SessionIDsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\")\n\x12SessionIDsResponse\x12\x13\n\x0bsession_ids\x18\x01 \x01(\t\"8\n\x11GetHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"6\n\x12GetHistoryResponse\x12 \n\x07history\x18\x01 \x01(\x0b\x32\x0f.ai.ChatMessage\"G\n\x0eGetChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\"#\n\x0fGetChatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"5\n\x10\x46irstChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"%\n\x11\x46irstChatResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xfe\x01\n\tAIService\x12@\n\rGetSessionIds\x12\x15.ai.SessionIDsRequest\x1a\x16.ai.SessionIDsResponse\"\x00\x12\x34\n\x07GetChat\x12\x12.ai.GetChatRequest\x1a\x13.ai.GetChatResponse\"\x00\x12=\n\nGetHistory\x12\x15.ai.GetHistoryRequest\x1a\x16.ai.GetHistoryResponse\"\x00\x12:\n\tFirstChat\x12\x14.ai.FirstChatRequest\x1a\x15.ai.FirstChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=24
  _globals['_CHATMESSAGE']._serialized_end=65
  _globals['_SESSIONIDSREQUEST']._serialized_start=67
  _globals['_SESSIONIDSREQUEST']._serialized_end=103
  _globals['_SESSIONIDSRESPONSE']._serialized_start=105
  _globals['_SESSIONIDSRESPONSE']._serialized_end=146
  _globals['_GETHISTORYREQUEST']._serialized_start=148
  _globals['_GETHISTORYREQUEST']._serialized_end=204
  _globals['_GETHISTORYRESPONSE']._serialized_start=206
  _globals['_GETHISTORYRESPONSE']._serialized_end=260
  _globals['_GETCHATREQUEST']._serialized_start=262
  _globals['_GETCHATREQUEST']._serialized_end=333
  _globals['_GETCHATRESPONSE']._serialized_start=335
  _globals['_GETCHATRESPONSE']._serialized_end=370
  _globals['_FIRSTCHATREQUEST']._serialized_start=372
  _globals['_FIRSTCHATREQUEST']._serialized_end=425
  _globals['_FIRSTCHATRESPONSE']._serialized_start=427
  _globals['_FIRSTCHATRESPONSE']._serialized_end=464
  _globals['_AISERVICE']._serialized_start=467
  _globals['_AISERVICE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
