# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionIds = channel.unary_unary(
                '/ai.AIService/GetSessionIds',
                request_serializer=ai__service__pb2.SessionIDsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SessionIDsResponse.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/ai.AIService/GetChat',
                request_serializer=ai__service__pb2.GetChatRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetChatResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/ai.AIService/GetHistory',
                request_serializer=ai__service__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetHistoryResponse.FromString,
                _registered_method=True)
        self.FirstChat = channel.unary_unary(
                '/ai.AIService/FirstChat',
                request_serializer=ai__service__pb2.FirstChatRequest.SerializeToString,
                response_deserializer=ai__service__pb2.FirstChatResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSessionIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FirstChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSessionIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionIds,
                    request_deserializer=ai__service__pb2.SessionIDsRequest.FromString,
                    response_serializer=ai__service__pb2.SessionIDsResponse.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=ai__service__pb2.GetChatRequest.FromString,
                    response_serializer=ai__service__pb2.GetChatResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=ai__service__pb2.GetHistoryRequest.FromString,
                    response_serializer=ai__service__pb2.GetHistoryResponse.SerializeToString,
            ),
            'FirstChat': grpc.unary_unary_rpc_method_handler(
                    servicer.FirstChat,
                    request_deserializer=ai__service__pb2.FirstChatRequest.FromString,
                    response_serializer=ai__service__pb2.FirstChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSessionIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetSessionIds',
            ai__service__pb2.SessionIDsRequest.SerializeToString,
            ai__service__pb2.SessionIDsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetChat',
            ai__service__pb2.GetChatRequest.SerializeToString,
            ai__service__pb2.GetChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetHistory',
            ai__service__pb2.GetHistoryRequest.SerializeToString,
            ai__service__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FirstChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/FirstChat',
            ai__service__pb2.FirstChatRequest.SerializeToString,
            ai__service__pb2.FirstChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
